# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ms.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(630, 555)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(110, 100, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.lw1 = QtWidgets.QListWidget(form1)
        self.lw1.setGeometry(QtCore.QRect(315, 110, 161, 221))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lw1.setFont(font)
        self.lw1.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.lw1.setObjectName("lw1")
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        self.l2 = QtWidgets.QLabel(form1)
        self.l2.setGeometry(QtCore.QRect(240, 400, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setText("")
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my code
        self.lw1.itemClicked.connect(self.fn1)
    def fn1(self):
        a=0
        for b in self.lw1.selectedItems():
            if b.text()=="Pencil":
                a=a+20
            elif b.text()=="Pen":
                a=a+50
            elif b.text()=="Notebook":
                a=a+60
            elif b.text()=="Eraser":
                a=a+5
            elif b.text()=="Scale":
                a=a+15
            elif b.text()=="Glue":
                a=a+20
            elif b.text()=="Stabler":
                a=a+40
        self.l2.setText("Rs." + str(a))
        
        

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "Multiselection List"))
        self.l1.setText(_translate("form1", "Products:"))
        __sortingEnabled = self.lw1.isSortingEnabled()
        self.lw1.setSortingEnabled(False)
        item = self.lw1.item(0)
        item.setText(_translate("form1", "Pencil"))
        item = self.lw1.item(1)
        item.setText(_translate("form1", "Pen"))
        item = self.lw1.item(2)
        item.setText(_translate("form1", "Notebook"))
        item = self.lw1.item(3)
        item.setText(_translate("form1", "Eraser"))
        item = self.lw1.item(4)
        item.setText(_translate("form1", "Scale"))
        item = self.lw1.item(5)
        item.setText(_translate("form1", "Glue"))
        item = self.lw1.item(6)
        item.setText(_translate("form1", "Stabler"))
        self.lw1.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
