# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(851, 408)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(80, 90, 701, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setStyleSheet("color:BLUE;\n"
"")
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.cb1 = QtWidgets.QComboBox(form1)
        self.cb1.setGeometry(QtCore.QRect(440, 290, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cb1.setFont(font)
        self.cb1.setStyleSheet("")
        self.cb1.setObjectName("cb1")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.l2 = QtWidgets.QLabel(form1)
        self.l2.setGeometry(QtCore.QRect(220, 290, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l2.setFont(font)
        self.l2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l2.setObjectName("l2")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my work
        self.cb1.currentIndexChanged.connect(self.fn1)
        
    def fn1(self):
        a=self.cb1.currentText()
        b="color:" + a +";"
        self.l1.setStyleSheet(b)

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "Color Change"))
        self.l1.setText(_translate("form1", "GAYATHRI PRASAD"))
        self.cb1.setCurrentText(_translate("form1", "BLUE"))
        self.cb1.setItemText(0, _translate("form1", "BLUE"))
        self.cb1.setItemText(1, _translate("form1", "RED"))
        self.cb1.setItemText(2, _translate("form1", "BLACK"))
        self.cb1.setItemText(3, _translate("form1", "PURPLE"))
        self.cb1.setItemText(4, _translate("form1", "ORANGE"))
        self.cb1.setItemText(5, _translate("form1", "GREEN"))
        self.l2.setText(_translate("form1", "Select the Color:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
