# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fees.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(439, 369)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(60, 40, 321, 81))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.c1 = QtWidgets.QCheckBox(form1)
        self.c1.setGeometry(QtCore.QRect(170, 170, 121, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c1.setFont(font)
        self.c1.setObjectName("c1")
        self.l2 = QtWidgets.QLabel(form1)
        self.l2.setGeometry(QtCore.QRect(130, 280, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my work
        self.c1.stateChanged.connect(self.fn1)
    def fn1(self):
        if self.c1.isChecked()==True:
            self.l2.setText("Rs.3000")
        else:
            self.l2.setText("Rs.10000")
    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "Fees Details"))
        self.l1.setText(_translate("form1", "FEES"))
        self.c1.setText(_translate("form1", "SC/ST"))
        self.l2.setText(_translate("form1", "Rs.10000"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
