# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fontfam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FORM1(object):
    def setupUi(self, FORM1):
        FORM1.setObjectName("FORM1")
        FORM1.resize(706, 365)
        self.l1 = QtWidgets.QLabel(FORM1)
        self.l1.setGeometry(QtCore.QRect(50, 80, 601, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.l1.setFont(font)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(FORM1)
        self.l2.setGeometry(QtCore.QRect(150, 240, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.fcb1 = QtWidgets.QFontComboBox(FORM1)
        self.fcb1.setGeometry(QtCore.QRect(310, 240, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fcb1.setFont(font)
        self.fcb1.setObjectName("fcb1")

        self.retranslateUi(FORM1)
        QtCore.QMetaObject.connectSlotsByName(FORM1)
        #my code
        self.fcb1.currentIndexChanged.connect(self.fn1)

    def fn1(self):
        a=self.fcb1.currentText()
        f=self.l1.font()
        f.setFamily(a)
        self.l1.setFont(f)

    def retranslateUi(self, FORM1):
        _translate = QtCore.QCoreApplication.translate
        FORM1.setWindowTitle(_translate("FORM1", "Font Combobox Demo"))
        self.l1.setText(_translate("FORM1", "GAYATHRI PRASAD"))
        self.l2.setText(_translate("FORM1", "Select Font:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FORM1 = QtWidgets.QWidget()
    ui = Ui_FORM1()
    ui.setupUi(FORM1)
    FORM1.show()
    sys.exit(app.exec_())
