# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(577, 389)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(70, 90, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.le1 = QtWidgets.QLineEdit(form1)
        self.le1.setGeometry(QtCore.QRect(300, 90, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le1.setFont(font)
        self.le1.setMaxLength(5)
        self.le1.setObjectName("le1")
        self.b1 = QtWidgets.QPushButton(form1)
        self.b1.setGeometry(QtCore.QRect(200, 170, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.l2 = QtWidgets.QLabel(form1)
        self.l2.setGeometry(QtCore.QRect(140, 260, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l2.setFont(font)
        self.l2.setText("")
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "OTP PIN PROJECT"))
        self.l1.setText(_translate("form1", "ENTER THE 5 DIGIT PIN:"))
        self.b1.setText(_translate("form1", "VERIFY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
