# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spinbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(680, 573)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(40, 60, 601, 211))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1.setFont(font)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(form1)
        self.l2.setGeometry(QtCore.QRect(150, 390, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l2.setFont(font)
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")
        self.SPIN1 = QtWidgets.QSpinBox(form1)
        self.SPIN1.setGeometry(QtCore.QRect(310, 390, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.SPIN1.setFont(font)
        self.SPIN1.setMinimum(10)
        self.SPIN1.setMaximum(110)
        self.SPIN1.setObjectName("SPIN1")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my work
        self.SPIN1.valueChanged.connect(self.fn1)

    def fn1(self):
        a=self.SPIN1.value()
        f=self.l1.font()
        f.setPointSize(a)
        self.l1.setFont(f)

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "Spin Box Demo"))
        self.l1.setText(_translate("form1", "GAYATHRI PRASAD"))
        self.l2.setText(_translate("form1", "Size:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
