# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(765, 246)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(10, 40, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.l1.setFont(font)
        self.l1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.l1.setObjectName("l1")
        self.le1 = QtWidgets.QLineEdit(form1)
        self.le1.setGeometry(QtCore.QRect(270, 40, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.le1.setFont(font)
        self.le1.setObjectName("le1")
        self.b1 = QtWidgets.QPushButton(form1)
        self.b1.setGeometry(QtCore.QRect(630, 40, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.cb1 = QtWidgets.QComboBox(form1)
        self.cb1.setGeometry(QtCore.QRect(120, 140, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.cb1.setFont(font)
        self.cb1.setObjectName("cb1")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.cb1.addItem("")
        self.b2 = QtWidgets.QPushButton(form1)
        self.b2.setGeometry(QtCore.QRect(490, 140, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my work
        self.b1.clicked.connect(self.fn1)
        self.b2.clicked.connect(self.fn2)

    def fn1(self):
        a=self.le1.text()
        self.cb1.addItem(a)
        self.le1.clear()

    def fn2(self):
        i=self.cb1.currentIndex()
        print(i)
        self.cb1.removeItem(i)

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "DAILY TASKS"))
        self.l1.setText(_translate("form1", "SET YOUR TASKS:"))
        self.b1.setText(_translate("form1", "ADD"))
        self.cb1.setItemText(0, _translate("form1", "Study ML for 1hr"))
        self.cb1.setItemText(1, _translate("form1", "Complete Mini Project 50%"))
        self.cb1.setItemText(2, _translate("form1", "Complete Assignment"))
        self.b2.setText(_translate("form1", "COMPLETED"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
