# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ts.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(435, 354)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(30, 30, 381, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.r1 = QtWidgets.QRadioButton(form1)
        self.r1.setGeometry(QtCore.QRect(60, 220, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.r1.setFont(font)
        self.r1.setObjectName("r1")
        self.r2 = QtWidgets.QRadioButton(form1)
        self.r2.setGeometry(QtCore.QRect(310, 220, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.r2.setFont(font)
        self.r2.setObjectName("r2")
        self.r4 = QtWidgets.QRadioButton(form1)
        self.r4.setGeometry(QtCore.QRect(310, 290, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.r4.setFont(font)
        self.r4.setObjectName("r4")
        self.r3 = QtWidgets.QRadioButton(form1)
        self.r3.setGeometry(QtCore.QRect(60, 290, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.r3.setFont(font)
        self.r3.setObjectName("r3")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        self.r1.toggled.connect(self.fn1)
        self.r2.toggled.connect(self.fn2)
        self.r3.toggled.connect(self.fn3)
        self.r4.toggled.connect(self.fn4)
    def fn1(self):
        f=self.l1.font()
        f.setPointSize(14)
        self.l1.setFont(f)
    def fn2(self):
        f=self.l1.font()
        f.setPointSize(16)
        self.l1.setFont(f)
    def fn3(self):
        f=self.l1.font()
        f.setPointSize(18)
        self.l1.setFont(f)
    def fn4(self):
        f=self.l1.font()
        f.setPointSize(20)
        self.l1.setFont(f)

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "Text Size Demo"))
        self.l1.setText(_translate("form1", "GAYATHRI PRASAD"))
        self.r1.setText(_translate("form1", "14"))
        self.r2.setText(_translate("form1", "16"))
        self.r4.setText(_translate("form1", "20"))
        self.r3.setText(_translate("form1", "18"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
