# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ledemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(550, 492)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(60, 120, 201, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.le1 = QtWidgets.QLineEdit(form1)
        self.le1.setEnabled(True)
        self.le1.setGeometry(QtCore.QRect(290, 120, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.le1.setFont(font)
        self.le1.setText("")
        self.le1.setClearButtonEnabled(False)
        self.le1.setObjectName("le1")
        self.b1 = QtWidgets.QPushButton(form1)
        self.b1.setGeometry(QtCore.QRect(180, 240, 161, 61))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.l2 = QtWidgets.QLabel(form1)
        self.l2.setGeometry(QtCore.QRect(154, 370, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setText("")
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my work
        self.b1.clicked.connect(self.fn1)
    def fn1(self):
        a=int(self.le1.text())
        if a>=50:
            self.l2.setText("PASS")
        else:
            self.l2.setText("FAIL")

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "Line Edit Demo"))
        self.l1.setText(_translate("form1", "Enter Your Mark:"))
        self.b1.setText(_translate("form1", "CLICK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
