# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maths.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form1(object):
    def setupUi(self, Form1):
        Form1.setObjectName("Form1")
        Form1.resize(430, 351)
        self.l1 = QtWidgets.QLabel(Form1)
        self.l1.setGeometry(QtCore.QRect(50, 50, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.le1 = QtWidgets.QLineEdit(Form1)
        self.le1.setGeometry(QtCore.QRect(210, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le1.setFont(font)
        self.le1.setObjectName("le1")
        self.l2 = QtWidgets.QLabel(Form1)
        self.l2.setGeometry(QtCore.QRect(50, 100, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.le2 = QtWidgets.QLineEdit(Form1)
        self.le2.setGeometry(QtCore.QRect(210, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le2.setFont(font)
        self.le2.setObjectName("le2")
        self.b1 = QtWidgets.QPushButton(Form1)
        self.b1.setGeometry(QtCore.QRect(30, 190, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(Form1)
        self.b2.setGeometry(QtCore.QRect(130, 190, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(Form1)
        self.b3.setGeometry(QtCore.QRect(230, 190, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.l3 = QtWidgets.QLabel(Form1)
        self.l3.setGeometry(QtCore.QRect(180, 270, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l3.setFont(font)
        self.l3.setText("")
        self.l3.setObjectName("l3")
        self.b4 = QtWidgets.QPushButton(Form1)
        self.b4.setGeometry(QtCore.QRect(330, 190, 75, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")

        self.retranslateUi(Form1)
        QtCore.QMetaObject.connectSlotsByName(Form1)
        #work
        self.b1.clicked.connect(self.fn1)
        self.b2.clicked.connect(self.fn2)
        self.b3.clicked.connect(self.fn3)
        self.b4.clicked.connect(self.fn4)

    def fn1(self):
        a=int( self.le1.text() )
        b=int( self.le2.text() )
        c=a+b
        self.l3.setText(str(c))

    def fn2(self):
        a=int( self.le1.text() )
        b=int( self.le2.text() )
        c=a-b
        self.l3.setText(str(c))

    def fn3(self):
        a=int( self.le1.text() )
        b=int( self.le2.text() )
        c=a*b
        self.l3.setText(str(c))

    def fn4(self):
        a=int( self.le1.text() )
        b=int( self.le2.text() )
        c=a/b
        self.l3.setText(str(c))

    def retranslateUi(self, Form1):
        _translate = QtCore.QCoreApplication.translate
        Form1.setWindowTitle(_translate("Form1", "Basic Maths"))
        self.l1.setText(_translate("Form1", "Enter a First int no. :"))
        self.l2.setText(_translate("Form1", "Enter a Second int no. :"))
        self.b1.setText(_translate("Form1", "Add"))
        self.b2.setText(_translate("Form1", "Sub"))
        self.b3.setText(_translate("Form1", "Mul"))
        self.b4.setText(_translate("Form1", "Div"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form1 = QtWidgets.QWidget()
    ui = Ui_Form1()
    ui.setupUi(Form1)
    Form1.show()
    sys.exit(app.exec_())
