# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(502, 392)
        form1.setStyleSheet("background-color: PINK;")
        self.lw1 = QtWidgets.QListWidget(form1)
        self.lw1.setGeometry(QtCore.QRect(260, 100, 151, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lw1.setFont(font)
        self.lw1.setObjectName("lw1")
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lw1.addItem(item)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(110, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(form1)
        self.l2.setGeometry(QtCore.QRect(110, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(form1)
        self.l3.setGeometry(QtCore.QRect(220, 290, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(12)
        self.l3.setFont(font)
        self.l3.setStyleSheet("")
        self.l3.setAlignment(QtCore.Qt.AlignCenter)
        self.l3.setObjectName("l3")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my code
        self.lw1.itemClicked.connect(self.fn1)

    def fn1(self):
        a=self.lw1.currentItem().text()
        if a=="PENCIL":
            self.l3.setText("Rs.15")
        elif a=="PEN":
            self.l3.setText("Rs.50")
        elif a=="NOTEBOOK":
            self.l3.setText("Rs.60")
        elif a=="ERASER":
            self.l3.setText("Rs.5")
        else:
            self.l3.setText(" ")

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "List Demo"))
        __sortingEnabled = self.lw1.isSortingEnabled()
        self.lw1.setSortingEnabled(False)
        item = self.lw1.item(0)
        item.setText(_translate("form1", "PENCIL"))
        item = self.lw1.item(1)
        item.setText(_translate("form1", "PEN"))
        item = self.lw1.item(2)
        item.setText(_translate("form1", "NOTEBOOK"))
        item = self.lw1.item(3)
        item.setText(_translate("form1", "ERASER"))
        self.lw1.setSortingEnabled(__sortingEnabled)
        self.l1.setText(_translate("form1", "PRODUCTS:"))
        self.l2.setText(_translate("form1", "PRICE:"))
        self.l3.setText(_translate("form1", " "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
