# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form2(object):
    def setupUi(self, Form2):
        Form2.setObjectName("Form2")
        Form2.resize(629, 464)
        font = QtGui.QFont()
        font.setPointSize(15)
        Form2.setFont(font)
        self.l1 = QtWidgets.QLabel(Form2)
        self.l1.setGeometry(QtCore.QRect(84, 50, 451, 101))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT Condensed")
        font.setPointSize(30)
        self.l1.setFont(font)
        self.l1.setText("")
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.b1 = QtWidgets.QPushButton(Form2)
        self.b1.setGeometry(QtCore.QRect(210, 220, 221, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(Form2)
        self.b2.setGeometry(QtCore.QRect(210, 270, 221, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(Form2)
        self.b3.setGeometry(QtCore.QRect(210, 320, 221, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(Form2)
        self.b4.setGeometry(QtCore.QRect(210, 370, 221, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")

        self.retranslateUi(Form2)
        QtCore.QMetaObject.connectSlotsByName(Form2)
        #my work
        self.b1.clicked.connect(self.fn1)
        self.b2.clicked.connect(self.fn2)
        self.b3.clicked.connect(self.fn3)
        self.b4.clicked.connect(self.fn4)

    def fn1(self):
        self.l1.setText("GAYATHRI PRASAD")
    def fn2(self):
        self.l1.setText("I CS(DSA)")
    def fn3(self):
        self.l1.setText("242204")
    def fn4(self):
        self.l1.setText("SLCS")
    

    def retranslateUi(self, Form2):
        _translate = QtCore.QCoreApplication.translate
        Form2.setWindowTitle(_translate("Form2", "MY DETAILS"))
        self.b1.setText(_translate("Form2", "MY NAME"))
        self.b2.setText(_translate("Form2", "CLASS"))
        self.b3.setText(_translate("Form2", "ROLL NO"))
        self.b4.setText(_translate("Form2", "COLLEGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form2 = QtWidgets.QWidget()
    ui = Ui_Form2()
    ui.setupUi(Form2)
    Form2.show()
    sys.exit(app.exec_())
