# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lablebtn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(828, 703)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(90, 160, 651, 91))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(20)
        self.l1.setFont(font)
        self.l1.setText("")
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.pushButton = QtWidgets.QPushButton(form1)
        self.pushButton.setGeometry(QtCore.QRect(320, 420, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my work
        self.pushButton.clicked.connect(self.fn1)

    def fn1(self):
        self.l1.setText("GAYATHRI PRASAD")

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "labelbutton"))
        self.pushButton.setText(_translate("form1", "SHOW NAME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
