# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(1356, 850)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        form1.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(form1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frame = QtWidgets.QFrame(form1)
        self.frame.setMinimumSize(QtCore.QSize(800, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.l1 = QtWidgets.QLabel(self.frame)
        self.l1.setGeometry(QtCore.QRect(60, 80, 681, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.l1.setFont(font)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.le1 = QtWidgets.QLineEdit(self.frame)
        self.le1.setGeometry(QtCore.QRect(50, 230, 701, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.le1.setFont(font)
        self.le1.setObjectName("le1")
        self.b1 = QtWidgets.QPushButton(self.frame)
        self.b1.setGeometry(QtCore.QRect(50, 370, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.frame)
        self.b2.setGeometry(QtCore.QRect(230, 370, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.frame)
        self.b3.setGeometry(QtCore.QRect(410, 370, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(self.frame)
        self.b4.setGeometry(QtCore.QRect(590, 370, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(self.frame)
        self.b5.setGeometry(QtCore.QRect(50, 460, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(self.frame)
        self.b6.setGeometry(QtCore.QRect(230, 460, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setObjectName("b6")
        self.b7 = QtWidgets.QPushButton(self.frame)
        self.b7.setGeometry(QtCore.QRect(410, 460, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QPushButton(self.frame)
        self.b8.setGeometry(QtCore.QRect(590, 460, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(self.frame)
        self.b9.setGeometry(QtCore.QRect(50, 550, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setObjectName("b9")
        self.b10 = QtWidgets.QPushButton(self.frame)
        self.b10.setGeometry(QtCore.QRect(230, 550, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b10.setFont(font)
        self.b10.setObjectName("b10")
        self.b11 = QtWidgets.QPushButton(self.frame)
        self.b11.setGeometry(QtCore.QRect(410, 550, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b11.setFont(font)
        self.b11.setObjectName("b11")
        self.b12 = QtWidgets.QPushButton(self.frame)
        self.b12.setGeometry(QtCore.QRect(590, 550, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b12.setFont(font)
        self.b12.setObjectName("b12")
        self.b13 = QtWidgets.QPushButton(self.frame)
        self.b13.setGeometry(QtCore.QRect(50, 640, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b13.setFont(font)
        self.b13.setObjectName("b13")
        self.b14 = QtWidgets.QPushButton(self.frame)
        self.b14.setGeometry(QtCore.QRect(230, 640, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b14.setFont(font)
        self.b14.setObjectName("b14")
        self.b15 = QtWidgets.QPushButton(self.frame)
        self.b15.setGeometry(QtCore.QRect(410, 640, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b15.setFont(font)
        self.b15.setObjectName("b15")
        self.b16 = QtWidgets.QPushButton(self.frame)
        self.b16.setGeometry(QtCore.QRect(590, 640, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.b16.setFont(font)
        self.b16.setObjectName("b16")
        self.b17 = QtWidgets.QPushButton(self.frame)
        self.b17.setGeometry(QtCore.QRect(50, 740, 341, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b17.setFont(font)
        self.b17.setObjectName("b17")
        self.b18 = QtWidgets.QPushButton(self.frame)
        self.b18.setGeometry(QtCore.QRect(410, 740, 341, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b18.setFont(font)
        self.b18.setObjectName("b18")
        self.horizontalLayout.addWidget(self.frame)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my code
        self.form1 = form1
        self.b1.clicked.connect(self.digit7)
        self.b2.clicked.connect(self.digit8)
        self.b3.clicked.connect(self.digit9)
        self.b5.clicked.connect(self.digit4)
        self.b6.clicked.connect(self.digit5)
        self.b7.clicked.connect(self.digit6)
        self.b9.clicked.connect(self.digit1)
        self.b10.clicked.connect(self.digit2)
        self.b11.clicked.connect(self.digit3)
        self.b13.clicked.connect(self.digit0)
        self.b4.clicked.connect(self.multiply)
        self.b8.clicked.connect(self.subtract)
        self.b12.clicked.connect(self.add)
        self.b14.clicked.connect(self.dot)
        self.b15.clicked.connect(self.divide)
        self.b16.clicked.connect(self.result)  
        self.b17.clicked.connect(self.clear)        
        self.b18.clicked.connect(self.delete)       
        self.expression = ""

    def add_digit(self, digit):
        self.expression += digit
        self.le1.setText(self.expression)

    def add_operator(self, operator):
        self.expression += operator
        self.le1.setText(self.expression)

    def digit7(self):
        self.add_digit("7")

    def digit8(self):
        self.add_digit("8")

    def digit9(self):
        self.add_digit("9")

    def digit4(self):
        self.add_digit("4")

    def digit5(self):
        self.add_digit("5")

    def digit6(self):
        self.add_digit("6")

    def digit1(self):
        self.add_digit("1")

    def digit2(self):
        self.add_digit("2")

    def digit3(self):
        self.add_digit("3")

    def digit0(self):
        self.add_digit("0")

    def multiply(self):
        self.add_operator("*")

    def subtract(self):
        self.add_operator("-")

    def add(self):
        self.add_operator("+")

    def dot(self):
        self.add_operator(".")

    def divide(self):
        self.add_operator("/")

    def result(self):
        try:
            self.expression = str(eval(self.expression))
            self.le1.setText(self.expression)
        except:
            self.le1.setText("Error")
            self.expression = ""

    def clear(self):
        self.expression = ""
        self.le1.setText("")

    def delete(self):
        self.expression = self.expression[:-1]
        self.le1.setText(self.expression)




    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "CALCULATOR"))
        self.l1.setText(_translate("form1", "BASIC CALCULATOR"))
        self.b1.setText(_translate("form1", "7"))
        self.b2.setText(_translate("form1", "8"))
        self.b3.setText(_translate("form1", "9"))
        self.b4.setText(_translate("form1", "x"))
        self.b5.setText(_translate("form1", "4"))
        self.b6.setText(_translate("form1", "5"))
        self.b7.setText(_translate("form1", "6"))
        self.b8.setText(_translate("form1", "-"))
        self.b9.setText(_translate("form1", "1"))
        self.b10.setText(_translate("form1", "2"))
        self.b11.setText(_translate("form1", "3"))
        self.b12.setText(_translate("form1", "+"))
        self.b13.setText(_translate("form1", "0"))
        self.b14.setText(_translate("form1", "."))
        self.b15.setText(_translate("form1", "/"))
        self.b16.setText(_translate("form1", "="))
        self.b17.setText(_translate("form1", "CLEAR"))
        self.b18.setText(_translate("form1", "DELETE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.showMaximized()
    sys.exit(app.exec_())
