# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imgdisplay.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(991, 729)
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(50, 40, 891, 531))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.l1.setFont(font)
        self.l1.setText("")
        self.l1.setPixmap(QtGui.QPixmap("work2.jpg"))
        self.l1.setScaledContents(True)
        self.l1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.l1.setObjectName("l1")
        self.b1 = QtWidgets.QPushButton(form1)
        self.b1.setGeometry(QtCore.QRect(100, 620, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(form1)
        self.b2.setGeometry(QtCore.QRect(590, 620, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Nirmala Text")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my work
        self.b1.clicked.connect(self.shinchan)
        self.b2.clicked.connect(self.naruto)

    def shinchan(self):
        self.l1.setPixmap(QtGui.QPixmap("shinchan.jpeg"))
        self.l1.setScaledContents(True)

    def naruto(self):
        self.l1.setPixmap(QtGui.QPixmap("naruto.jpeg"))
        self.l1.setScaledContents(True)                          

    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "IMAGE DISPLAY"))
        self.b1.setText(_translate("form1", "SHINCHAN"))
        self.b2.setText(_translate("form1", "NARUTO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
