# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'range.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form1(object):
    def setupUi(self, form1):
        form1.setObjectName("form1")
        form1.resize(594, 512)
        self.hsb1 = QtWidgets.QScrollBar(form1)
        self.hsb1.setGeometry(QtCore.QRect(50, 60, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hsb1.setFont(font)
        self.hsb1.setMinimum(1)
        self.hsb1.setMaximum(150)
        self.hsb1.setProperty("value", 50)
        self.hsb1.setOrientation(QtCore.Qt.Horizontal)
        self.hsb1.setObjectName("hsb1")
        self.l1 = QtWidgets.QLabel(form1)
        self.l1.setGeometry(QtCore.QRect(470, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1.setFont(font)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setObjectName("l1")
        self.hs1 = QtWidgets.QSlider(form1)
        self.hs1.setGeometry(QtCore.QRect(40, 130, 381, 51))
        self.hs1.setMinimum(1)
        self.hs1.setMaximum(150)
        self.hs1.setProperty("value", 80)
        self.hs1.setOrientation(QtCore.Qt.Horizontal)
        self.hs1.setObjectName("hs1")
        self.l2 = QtWidgets.QLabel(form1)
        self.l2.setGeometry(QtCore.QRect(470, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l2.setFont(font)
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setObjectName("l2")
        self.vsb1 = QtWidgets.QScrollBar(form1)
        self.vsb1.setGeometry(QtCore.QRect(50, 210, 41, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.vsb1.setFont(font)
        self.vsb1.setMinimum(1)
        self.vsb1.setMaximum(150)
        self.vsb1.setProperty("value", 110)
        self.vsb1.setOrientation(QtCore.Qt.Vertical)
        self.vsb1.setObjectName("vsb1")
        self.l3 = QtWidgets.QLabel(form1)
        self.l3.setGeometry(QtCore.QRect(150, 310, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l3.setFont(font)
        self.l3.setAlignment(QtCore.Qt.AlignCenter)
        self.l3.setObjectName("l3")
        self.vs1 = QtWidgets.QSlider(form1)
        self.vs1.setGeometry(QtCore.QRect(310, 210, 41, 261))
        self.vs1.setMinimum(1)
        self.vs1.setMaximum(150)
        self.vs1.setProperty("value", 130)
        self.vs1.setOrientation(QtCore.Qt.Vertical)
        self.vs1.setObjectName("vs1")
        self.l4 = QtWidgets.QLabel(form1)
        self.l4.setGeometry(QtCore.QRect(400, 310, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l4.setFont(font)
        self.l4.setAlignment(QtCore.Qt.AlignCenter)
        self.l4.setObjectName("l4")

        self.retranslateUi(form1)
        QtCore.QMetaObject.connectSlotsByName(form1)
        #my code
        self.hsb1.valueChanged.connect(self.fn1)
        self.vsb1.valueChanged.connect(self.fn2)
        self.hs1.valueChanged.connect(self.fn3)
        self.vs1.valueChanged.connect(self.fn4)

    def fn1(self):
        a=self.hsb1.value()
        self.l1.setText(str(a))

    
    def fn2(self):
        a=self.vsb1.value()
        self.l3.setText(str(a))

    
    def fn3(self):
        a=self.hs1.value()
        self.l2.setText(str(a))

    
    def fn4(self):
        a=self.vs1.value()
        self.l4.setText(str(a))
    def retranslateUi(self, form1):
        _translate = QtCore.QCoreApplication.translate
        form1.setWindowTitle(_translate("form1", "Scrollbar and Slidebar demo"))
        self.l1.setText(_translate("form1", "50"))
        self.l2.setText(_translate("form1", "80"))
        self.l3.setText(_translate("form1", "110"))
        self.l4.setText(_translate("form1", "130"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form1 = QtWidgets.QWidget()
    ui = Ui_form1()
    ui.setupUi(form1)
    form1.show()
    sys.exit(app.exec_())
